### ISSUE TITLE
russian and japanese languages do not seem to work

### ISSUE THREAD

**Issue by vesper8** [BruceJillis/PHP-Language-Detection#2]
Hi there! I've been using your class to guess the language of youtube titles/descriptions that I retrieve via their API. It's very useful so far and works pretty well.

I tried adding the russian language by following your instructions from https://github.com/BruceJillis/PHP-Language-Detection/issues/1

I notice that when I rebuild the .dat file after adding Russian the size of the .dat file does not change at all (still 79kb) even though the russian.raw file I am pointing it to is 30kb big with many random russian vocabulary. Further testing also shows that when including or not the japanese.raw file the size of the .dat file barely changes as well. I noticed that both japanese and russian have in common that they use a different alphabet from all other latin derived languages.

I have run the prediction function on text that is very clearly japanese and spanish and it always returns english as a detected language.

Do you have any idea what is causing this by any chance?

Thanks for your great library!

**Comment by BruceJillis** [comment]
He Vesper,

I'm on mobile so please forgive me any spelling errors.. 

So i just tried and added the included japanese file and added a small test case which did work for me. I'm at work so I can't spend much more time on it but I just wanted to report that in advance.

Are you sure the user under which the server is running has enough rights too delete/create files?

I will look into it some more tonight and might even add russian as a supported language out of the box .. especially if you could supply me with some russian text resources (specifically representative text, simple and complex).

Thanks for the compliment!

**Comment by BruceJillis** [comment]
So I did manage to check it out yesterday but wasn't able to update you on the results. For me the script with Japanese is working perfectly under a stock xampp install. Training on non-latin languages is working fine and I even did a (small) test on russian text .. which was also working fine. It's looking like my weekend is becoming pretty full so I may/or may not update the library to include russian but I'll do that out of bounds with this ticket, which i'm going to close.

Maybe you can try using the full.dat NGramProfile instead of the default one? The example script by default only trains on a couple of languages but the full ngram profile has been trained on japanese as well and is detecting the language correctly on a couple of sentences I grabbed from here:
http://www.linguanaut.com/english_japanese.htm

good luck!
